version: '2'

services:
  icecast:
#    image: vitiman/alpine-icecast:latest
    build: icecast
    ports:
      - "8000:8000"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.2

  musicdeamon:
    build: musicdaemon
    ports:
      - "9000:9000"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.3
    volumes:
      - ./volumes:/srv/media

  backend:
    build: backend
    environment:
      DB_NAME: radio-dev
      DB_HOST: 34.66.75.237
      DB_USERNAME: postgres
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      DJANGO_SETTINGS: local
    ports:
      - "8080:8080"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.4
    volumes:
      - ~/.config/gcloud/:/root/.config/gcloud

networks:
  apoweroftrance:
    driver: bridge
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
