version: '2'

services:
  icecast:
#    build: icecast
    image: gcr.io/apoweroftrance/icecast2:2.4.4
    ports:
      - "8000:8000"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.2
    volumes:
      - ./icecast.xml:/usr/share/icecast/icecast.xml

  musicdeamon:
#    build: musicdaemon
    image: gcr.io/apoweroftrance/musicdaemon:0.0.1
    environment:
      FUSE: gcs
      BUCKET: apoweroftrance-media
      GOOGLE_APPLICATION_CREDENTIALS: /root/service-account-key.json
    privileged: true
    ports:
      - "9000:9000"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.3
    volumes:
      - ./config.ini:/opt/musicdaemon/config.ini
      - ./apoweroftrance-525255671db2.json:/root/service-account-key.json
#      - ./volumes:/srv/media

  backend:
    build: backend
    environment:
      DB_NAME: radio-dev
      DB_HOST: 34.66.75.237
      DB_USERNAME: postgres
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      DJANGO_SETTINGS: local
    ports:
      - "8080:8080"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.4
    volumes:
      - ~/.config/gcloud/:/root/.config/gcloud

networks:
  apoweroftrance:
    driver: bridge
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
