version: '3'

services:
  icecast:
    container_name: icecast
    restart: always
    image: gcr.io/apoweroftrance/icecast2:latest
    ports:
      - "8000:8000"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.2
    volumes:
      - ./icecast.xml:/usr/share/icecast/icecast.xml

  musicdeamon:
    container_name: musicdaemon
    restart: always
    image: gcr.io/apoweroftrance/musicdaemon:latest
#    build: musicdaemon
    ports:
      - "9000:9000"
    depends_on:
      - gcsfuse
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.3
    volumes:
      - musicdaemon_data:/opt/musicdaemon
      - ./config.ini:/opt/musicdaemon/config.ini
#      - ./volumes:/srv/media:ro


  gcsfuse:
    container_name: gcsfuse
    image: gcr.io/apoweroftrance/gcsfuse:latest
    environment:
      MOUNT_POINT: /srv/media
      BUCKET: apoweroftrance-media
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    volumes:
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json

  nginx:
    container_name: nginx
    restart: always
    image: gcr.io/apoweroftrance/nginx:latest
    ports:
      - "80:80"
    volumes:
      - radio_data:/backend
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/sites-available/default:/etc/nginx/sites-available/default
      - ./nginx/config/useragent.rules:/etc/nginx/useragent.rules
      - ./nginx/config/cors:/etc/nginx/cors
      - ./nginx/config/whitelist.conf:/etc/nginx/whitelist.conf
    depends_on:
      - radio
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.4

  radio:
    container_name: radio
    restart: always
    image: gcr.io/apoweroftrance/radio:latest
#    build: backend
    environment:
      DB_NAME: radio-dev
      DB_HOST: 34.66.75.237
      DB_USERNAME: postgres
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /backend/service-account-key.json
    volumes:
      - radio_data:/backend
      - ./apoweroftrance-525255671db2.json:/backend/service-account-key.json
#      - ~/.config/gcloud/:/home/ubuntu/.config/gcloud

volumes:
  radio_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radio/backend #NOTE needs full path (~ doesn't work)
      o: bind
  musicdaemon_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radio/musicdaemon #NOTE needs full path (~ doesn't work)
      o: bind

networks:
  apoweroftrance:
    driver: bridge
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 10.0.0.0/16
