version: '3'

# https://www.44bits.io/ko/post/almost-perfect-development-environment-with-docker-and-docker-compose

services:
  icecast:
    container_name: icecast
    restart: always
    image: gcr.io/apoweroftrance/icecast2:latest
    ports:
      - "8000:8000"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.2
    volumes:
      - ./icecast.xml:/usr/share/icecast/icecast.xml

  musicdeamon:
    container_name: musicdaemon
    restart: always
    image: gcr.io/apoweroftrance/musicdaemon:dev-pod
#    image: gcr.io/apoweroftrance/musicdaemon:production-latest
#    build: musicdaemon
    environment:
      FUSE: gcs
      BUCKET: apoweroftrance-dev-media
      MOUNT_POINT: /srv/media
      WAIT_SERVICE: 1
      WAIT_URL: 10.0.0.7
      WAIT_PORT: 8090
      INSTALL: 0
      AUTOSTART: 1
    # https://stackoverflow.com/questions/33887194/how-to-set-multiple-commands-in-one-yaml-file-with-kubernetes
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    ports:
      - "9000:9000"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.3
    volumes:
      - musicdaemon_data:/opt/musicdaemon
      - ./config.ini:/opt/musicdaemon/config.ini
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json
#      - ./volumes:/mnt:ro

  db:
    container_name: db
    image: postgres:11.6
    environment:
      POSTGRES_USER: whiteblue3
      POSTGRES_PASSWORD: ?!Triace07
      POSTGRES_DB: apoweroftrance
      PGDATA: /var/postgres_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.4
    volumes:
#      - ./initialize_postgresql_multiple_databases.sh:/docker-entrypoint-initdb.d/initialize_postgresql_multiple_databases.sh
      - pgdata:/var/postgres_data

  redis:
    container_name: redis
    restart: always
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.5

  nginx:
    container_name: nginx
    restart: always
#    image: nginxinc/nginx-unprivileged:latest
    image: gcr.io/apoweroftrance/nginx:latest
#    build: nginx
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    # https://yeti.tistory.com/218
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/useragent.rules:/etc/nginx/useragent.rules
      - ./nginx/cors:/etc/nginx/cors
      - ./nginx/whitelist.conf:/etc/nginx/whitelist.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.6
    depends_on:
      - radio
      - account
      - post
      - admin
    links:
      - radio
      - account
      - post
      - admin

  radio:
    container_name: radio
    restart: always
    image: gcr.io/apoweroftrance/radio:dev-pod
#    image: gcr.io/apoweroftrance/radio:production-latest
#    build: radio
    environment:
      ENABLE_SWAGGER: 1
      DB_NAME: apoweroftrance
      DB_HOST: 10.0.0.4
      DB_USERNAME: whiteblue3
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      NGINX: 10.0.0.6:8080
      REDIS_URL: 10.0.0.5
      REDIS_PORT: 6379
      REDIS_DB: 0
      WAIT_SERVICE: 1
      WAIT_URL: 10.0.0.8
      WAIT_PORT: 8091
      INSTALL: 1
      MIGRATE: 1
      AUTOSTART: 1
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    ports:
      - "8090:8090"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.7
    volumes:
      - radio_data:/backend
      - ./radio_secret.json:/backend/secret.json
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json

  account:
    container_name: account
    restart: always
    image: gcr.io/apoweroftrance/account:dev-pod
#    image: gcr.io/apoweroftrance/account:production-latest
#    build: account
    environment:
      ENABLE_SWAGGER: 1
      DB_NAME: apoweroftrance
      DB_HOST: 10.0.0.4
      DB_USERNAME: whiteblue3
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      NGINX: 10.0.0.6:8081
      REDIS_URL: 10.0.0.5
      REDIS_PORT: 6379
      REDIS_DB: 0
      WAIT_SERVICE: 1
      WAIT_URL: 10.0.0.4
      WAIT_PORT: 5432
      INSTALL: 1
      MIGRATE: 1
      AUTOSTART: 1
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    ports:
      - "8091:8091"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.8
    volumes:
      - account_data:/backend
      - ./account_secret.json:/backend/secret.json
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json

  upload:
    container_name: upload
    restart: always
    image: gcr.io/apoweroftrance/upload:dev-pod
#    image: gcr.io/apoweroftrance/upload:production-latest
#    build: upload
    environment:
      ENABLE_SWAGGER: 1
      ENABLE_EMAIL_SEND: 1
      DB_NAME: apoweroftrance
      DB_HOST: 10.0.0.4
      DB_USERNAME: whiteblue3
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      NGINX: 10.0.0.6:8082
      REDIS_URL: 10.0.0.5
      REDIS_PORT: 6379
      REDIS_DB: 0
      WAIT_SERVICE: 1
      WAIT_URL: 10.0.0.8
      WAIT_PORT: 8091
      INSTALL: 1
      MIGRATE: 1
      AUTOSTART: 1
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    ports:
      - "8092:8092"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.9
    volumes:
      - upload_data:/backend
      - ./upload_secret.json:/backend/secret.json
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json

  cms:
    container_name: cms
    restart: always
    image: gcr.io/apoweroftrance/cms:production-latest
#    build: ../cms
    environment:
      DB_NAME: apoweroftrance
      DB_HOST: 10.0.0.4
      DB_USERNAME: whiteblue3
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      NGINX: 10.0.0.6:8083
      REDIS_URL: 10.0.0.5
      REDIS_PORT: 6379
      REDIS_DB: 0
      WAIT_SERVICE: 1
      WAIT_URL: 10.0.0.8
      WAIT_PORT: 8091
      INSTALL: 0
      MIGRATE: 0
      AUTOSTART: 1
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    ports:
      - "8093:8093"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.10
    volumes:
#      - upload_data:/backend
      - ./cms_secret.json:/backend/secret.json
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json

  post:
    container_name: post
    restart: always
    image: gcr.io/apoweroftrance/post:dev-pod
#    image: gcr.io/apoweroftrance/post:production-latest
#    build: post
    environment:
      ENABLE_SWAGGER: 1
      ENABLE_EMAIL_SEND: 1
      DB_NAME: apoweroftrance
      DB_HOST: 10.0.0.4
      DB_USERNAME: whiteblue3
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      NGINX: 10.0.0.6:8084
      REDIS_URL: 10.0.0.5
      REDIS_PORT: 6379
      REDIS_DB: 0
      WAIT_SERVICE: 1
      WAIT_URL: 10.0.0.7
      WAIT_PORT: 8091
      INSTALL: 1
      MIGRATE: 1
      AUTOSTART: 1
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    ports:
      - "8094:8094"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.11
    volumes:
      - post_data:/backend
      - ./post_secret.json:/backend/secret.json
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json

  admin:
    container_name: admin
    restart: always
    image: gcr.io/apoweroftrance/admin:dev-pod
#    image: gcr.io/apoweroftrance/admin:production-latest
#    build: admin
    environment:
      ENABLE_SWAGGER: 1
      ENABLE_EMAIL_SEND: 1
      DB_NAME: apoweroftrance
      DB_HOST: 10.0.0.4
      DB_USERNAME: whiteblue3
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      NGINX: 10.0.0.6:8085
      REDIS_URL: 10.0.0.5
      REDIS_PORT: 6379
      REDIS_DB: 0
      WAIT_SERVICE: 1
      WAIT_URL: 10.0.0.11
      WAIT_PORT: 8091
      INSTALL: 1
      MIGRATE: 1
      AUTOSTART: 1
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    ports:
      - "8095:8095"
    networks:
      apoweroftrance:
        ipv4_address: 10.0.0.12
    volumes:
      - admin_data:/backend
      - ./admin_secret.json:/backend/secret.json
      - ./apoweroftrance-525255671db2.json:/etc/gcloud/service-account-key.json

#  ffmpeg:
#    container_name: ffmpeg
#    restart: always
#    image: jrottenberg/ffmpeg:latest
#    hostname: ffmpeg
#    environment:
#      ICECAST_URL: http://10.0.0.2:8000/yui
#      CHANNEL: "A Power of Trance\nCH.YUI"
#      YOUTUBE_URL: rtmp://a.rtmp.youtube.com/live2/52my-hved-tvpe-r0t3-fb6e
#    volumes:
#      - ./ffmpeg/apoweroftrance.png:/srv/apoweroftrance.png
#      - ./ffmpeg/startup.sh:/scripts/startup.sh
#      - ./ffmpeg/live-meta.sh:/scripts/live-meta.sh
#      - ./ffmpeg/Fatsans.ttf:/srv/Fatsans.ttf
#      - ./ffmpeg/NanumGothic.ttf:/srv/NanumGothic.ttf
#      - ./ffmpeg/NanumGothicBold.ttf:/srv/NanumGothicBold.ttf
#    entrypoint: /scripts/startup.sh
#    networks:
#      apoweroftrance:
#        ipv4_address: 10.0.0.13


volumes:
  account_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radiosystem/account #NOTE needs full path (~ doesn't work)
      o: bind
  radio_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radiosystem/radio #NOTE needs full path (~ doesn't work)
      o: bind
  upload_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radiosystem/upload #NOTE needs full path (~ doesn't work)
      o: bind
  post_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radiosystem/post #NOTE needs full path (~ doesn't work)
      o: bind
  admin_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radiosystem/admin #NOTE needs full path (~ doesn't work)
      o: bind
  musicdaemon_data:
    driver_opts:
      type: none
      device: /Users/whiteblue3/Documents/dev/projects/apoweroftrance.com/source/radiosystem/musicdaemon #NOTE needs full path (~ doesn't work)
      o: bind
  pgdata:

networks:
  apoweroftrance:
    driver: bridge
    driver_opts:
      encrypted: "true"
    ipam:
      config:
        - subnet: 10.0.0.0/16
