version: '2'

services:
  icecast:
#    image: vitiman/alpine-icecast:latest
    build: icecast
    ports:
      - "8000:8000"
    networks:
      - music_stack

  musicdeamon:
    build: musicdaemon
    environment:
      DB_NAME: radio-dev
      DB_HOST: 34.66.75.237
      DB_USERNAME: postgres
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
    depends_on:
      - icecast
    ports:
      - "9000:9000"
    networks:
      - music_stack
    volumes:
      - ./volumes:/srv/media

  backend:
    build: backend
    environment:
      DB_NAME: radio-dev
      DB_HOST: 34.66.75.237
      DB_USERNAME: postgres
      DB_PASSWORD: ?!Triace07
      DB_PORT: 5432
      DJANGO_SETTINGS: local
    ports:
      - "8080:8080"
    networks:
      - music_stack

networks:
  music_stack:
    driver: bridge
