# Generated by Django 2.2.24 on 2021-06-16 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0007_auto_20210609_1440'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('spamuser', 'Spam User'), ('copyright', 'Copyright Claim')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('opened', 'Opened Issue'), ('accept', 'Accepted'), ('closed', 'Closed Issue')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Claim.accepter+', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Claim.issuer+', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Claim.track+', to='radio.Track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Claim.user+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claim',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='radio.Track')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='ClaimReply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='post.Claim')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ClaimReply',
                'verbose_name_plural': 'ClaimReply',
            },
        ),
    ]
