# Generated by Django 2.2.24 on 2021-06-16 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210616_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='issue',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Claim.issuer+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimreply',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Claim'),
        ),
        migrations.AlterField(
            model_name='claimreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
