# Generated by Django 2.2.24 on 2021-06-21 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20210616_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('notification', 'Notification'), ('claim_user', 'User Claim'), ('claim_copyright', 'Copyright Claim')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Notification')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_notification_targets',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='targets',
            field=models.ManyToManyField(blank=True, through='post.NotificationUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
