# Generated by Django 2.2.24 on 2021-06-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210621_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='staff_action',
            field=models.CharField(choices=[('noaction', 'No Action'), ('approved', 'Approved'), ('hold', 'Hold')], default='noaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='category',
            field=models.CharField(choices=[('issue', 'General Issue'), ('spamuser', 'Spam User'), ('copyright', 'Copyright Claim')], default='issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened Issue'), ('accept', 'Accepted'), ('closed', 'Closed Issue')], default='opened', max_length=20),
        ),
    ]
