# Generated by Django 2.2.24 on 2021-06-23 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_auto_20210623_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DirectMessage.send_user+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DirectMessage.target_user+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DirectMessage',
                'verbose_name_plural': 'DirectMessage',
            },
        ),
    ]
