# Generated by Django 2.2.24 on 2021-07-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20210609_1440'),
        ('post', '0006_directmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Track')),
            ],
            options={
                'verbose_name': 'TrackTag',
                'verbose_name_plural': 'TrackTag',
            },
        ),
    ]
