# Generated by Django 2.2.24 on 2021-07-08 07:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_tracktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', null=True),
        ),
    ]
