# Generated by Django 2.2 on 2020-04-10 03:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField()),
                ('format', models.CharField(choices=[('mp3', 'MP3')], default='mp3', max_length=3)),
                ('is_service', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField()),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('channel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('yui', 'YUI')], default='yui', max_length=15), size=None)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '음원',
                'verbose_name_plural': '음원',
            },
        ),
        migrations.CreateModel(
            name='PlayQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('yui', 'YUI')], default='yui', max_length=15)),
                ('will_play_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Track')),
            ],
            options={
                'verbose_name': '편성표',
                'verbose_name_plural': '편성표',
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('yui', 'YUI')], default='yui', max_length=15)),
                ('played_at', models.DateTimeField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Track')),
            ],
            options={
                'verbose_name': '송출 이력',
                'verbose_name_plural': '송출 이력',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요',
            },
        ),
    ]
