# Generated by Django 2.2 on 2020-04-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Like'},
        ),
        migrations.AlterModelOptions(
            name='playhistory',
            options={'verbose_name': 'Play History', 'verbose_name_plural': 'Play History'},
        ),
        migrations.AlterModelOptions(
            name='playqueue',
            options={'verbose_name': 'Play List', 'verbose_name_plural': 'Play List'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
