# Generated by Django 2.2 on 2020-04-14 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20200415_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='playhistory',
            name='artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playqueue',
            name='artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playqueue',
            name='location',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playqueue',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radio.Track'),
        ),
    ]
