# Generated by Django 2.2 on 2020-04-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20200415_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playqueue',
            name='will_play_at',
        ),
    ]
