# Generated by Django 2.2 on 2020-04-21 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20200421_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='track',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='radio.Track'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='artist',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='channel',
            field=models.CharField(choices=[('yui', 'YUI')], default='yui', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='played_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='track',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radio.Track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='last_played_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='play_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
