# Generated by Django 2.2.12 on 2021-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='access_type',
            field=models.CharField(choices=[(None, 'None'), ('authenticate', 'Authenticate'), ('logout', 'Logout'), ('ban', 'Ban')], default=None, max_length=50, null=True),
        ),
    ]
