# Generated by Django 2.2.12 on 2021-06-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
