# Generated by Django 2.2.12 on 2021-06-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_uploadable',
            field=models.BooleanField(default=True),
        ),
    ]
