# Generated by Django 2.2.12 on 2020-05-05 02:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=254)),
                ('format', models.CharField(choices=[('mp3', 'MP3')], default='mp3', max_length=3)),
                ('is_service', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField()),
                ('play_count', models.PositiveIntegerField(default=0, editable=False)),
                ('channel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('yui', 'YUI')], default='yui', max_length=15), size=None)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_played_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Music',
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('artist', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('channel', models.CharField(choices=[('yui', 'YUI')], default='yui', editable=False, max_length=15)),
                ('played_at', models.DateTimeField(editable=False)),
                ('track', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radio.Track')),
            ],
            options={
                'verbose_name': 'Play History',
                'verbose_name_plural': 'Play History',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='radio.Track')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Like',
            },
        ),
    ]
