# Generated by Django 2.2.12 on 2020-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20200509_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhistory',
            name='artist',
            field=models.CharField(blank=True, editable=False, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
