# Generated by Django 2.2.12 on 2021-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20200511_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_art',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
