# Generated by Django 2.2.12 on 2021-05-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_track_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='like_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
