# Generated by Django 2.2.24 on 2021-08-23 08:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0007_auto_20210609_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='listen_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='channel',
            field=models.CharField(choices=[('yui', 'YUI'), ('alice', 'ALICE'), ('miku', 'MIKU'), ('lena', 'LENA')], default='yui', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='track',
            name='channel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('yui', 'YUI'), ('alice', 'ALICE'), ('miku', 'MIKU'), ('lena', 'LENA')], default='yui', max_length=15), size=None),
        ),
        migrations.CreateModel(
            name='ListenHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('artist', models.CharField(blank=True, editable=False, max_length=70, null=True)),
                ('played_at', models.DateTimeField(editable=False)),
                ('track', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radio.Track')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listen History',
                'verbose_name_plural': 'Listen History',
            },
        ),
    ]
