# Generated by Django 2.2.24 on 2021-09-22 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0008_auto_20210823_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenhistory',
            name='is_pronunciatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listenhistory',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ListenHistory.provider+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listenhistory',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ListenHistory.user+', to=settings.AUTH_USER_MODEL),
        ),
    ]
