# Generated by Django 2.2.24 on 2021-09-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_auto_20210922_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_pronunciatable',
            field=models.BooleanField(default=False),
        ),
    ]
