apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcsfuse
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcsfuse
    spec:
      containers:
        - name: gcsfuse
          image: gcr.io/apoweroftrance/gcsfuse:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            postStart:
              exec:
                command: ["gcsfuse", "-o", "nonempty", "apoweroftrance-media", "/srv/media"]
            preStop:
              exec:
                command: ["fusermount", "-u", "/srv/media"]